CREATE DATABASE BDC_RH

USE BDC_RH

/* CRIAÇÃO DAS TABELAS */

CREATE TABLE CARGO(
	IDCARGO INT PRIMARY KEY IDENTITY,
	NOME_CARGO VARCHAR(30) NOT NULL,
	SALARIO_BASE DECIMAL(10,2) NOT NULL

)
GO

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	SEXO CHAR(1) NOT NULL,
	CHECK(SEXO IN('M','F')),
	DATA_NASCIMENTO DATE NOT NULL,
	DATA_ADMISSAO DATE NOT NULL,
	EMAIL VARCHAR(60) NOT NULL UNIQUE,
	STATUS VARCHAR(10) NOT NULL,
	ID_CARGO INT,
	ID_DEPARTAMENTO INT

)
GO

CREATE TABLE DEPENDENTE(
	IDDEPENDENTES INT PRIMARY KEY IDENTITY,
	NOME_DEPENDENTE VARCHAR(50) NOT NULL,
	PARENTESCO VARCHAR(30) NOT NULL,
	ID_FUNCIONARIO INT

)
GO

CREATE TABLE TELEFONE_FUNC(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(12) NOT NULL,
	CHECK(TIPO IN('RES','COM','CEL')),
	ID_FUNCIONARIO INT

)
GO

CREATE TABLE FALTA(
	IDFALTA INT PRIMARY KEY IDENTITY,
	MOTIVO VARCHAR(60) NOT NULL,
	DATA_FALTA DATE NOT NULL,
	ID_FUNCIONARIO INT

)
GO

CREATE TABLE SALARIO(
	IDSALARIO INT PRIMARY KEY IDENTITY,
	DATA_INICIO DATE NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	DATA_FIM DATE,
	ID_FUNCIONARIO INT

)
GO

CREATE TABLE BENEFICIO(
	IDBENEFICIO INT PRIMARY KEY IDENTITY,
	NOME_BENEFICIO VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(60) NOT NULL

)
GO



CREATE TABLE FUNCIONARIO_BENEFICIO(
	ID_FUNCIONARIO_BENEFICIO INT PRIMARY KEY IDENTITY,
	ID_FUNCIONARIO INT,
	ID_BENEFICIO INT,
	VALOR DECIMAL(10,2) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE 


)
GO


CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT PRIMARY KEY IDENTITY,
	NOME_DEPART VARCHAR(30) NOT NULL,

)
GO
