/* PROCEDURE DE REGISTRAR FALTA */

CREATE PROCEDURE REGISTRAR_FALTA
	   @ID_FUNCIONARIO INT,
	   @MOTIVO VARCHAR(50)
AS
BEGIN
		INSERT INTO FALTA (MOTIVO,DATA_FALTA,ID_FUNCIONARIO)
		VALUES (@MOTIVO,GETDATE(),@ID_FUNCIONARIO)
END
GO

EXEC REGISTRAR_FALTA 1,'Consulta médica'

/*  Procedure de Atualizar salário (histórico) */

CREATE PROCEDURE ATUALIZAR_SALARIO
	   @ID_FUNCIONARIO INT,
	   @NOVO_SALARIO DECIMAL(10,2)
AS
BEGIN
		UPDATE SALARIO
		SET DATA_FIM = GETDATE()
		WHERE ID_FUNCIONARIO = @ID_FUNCIONARIO
		AND DATA_FIM IS NULL
	    
		INSERT INTO SALARIO (DATA_INICIO,VALOR,ID_FUNCIONARIO)
		VALUES ( GETDATE(),@NOVO_SALARIO,@ID_FUNCIONARIO)
END
GO

EXEC ATUALIZAR_SALARIO 11,2800.00

/* PROCEDURES */

/* Procedure: Admitir funcionário*/

CREATE PROCEDURE ADMITIR_FUNC
	   @NOME VARCHAR(50),
	   @CPF VARCHAR(15),
	   @SEXO CHAR(1),
	   @DATA_NASCIMENTO DATE,
	   @EMAIL VARCHAR(50),
	   @STATUS VARCHAR(10),
	   @ID_CARGO INT,
	   @ID_DEPARTAMENTO INT,
	   @SALARIO DECIMAL(10,2),
	   @CIDADE VARCHAR(50),
	   @DATA_DEMISSAO DATE

AS
BEGIN
		INSERT INTO FUNCIONARIO(NOME,CPF,SEXO,DATA_NASCIMENTO,DATA_ADMISSAO,EMAIL,STATUS,ID_CARGO,ID_DEPARTAMENTO,CIDADE,DATA_DEMISSAO) 
		VALUES (@NOME,@CPF,@SEXO,@DATA_NASCIMENTO,GETDATE(),@EMAIL,@STATUS,@ID_CARGO,@ID_DEPARTAMENTO,@CIDADE,@DATA_DEMISSAO)

		DECLARE @ID_FUNC INT = SCOPE_IDENTITY()

		INSERT INTO SALARIO(DATA_INICIO,VALOR,ID_FUNCIONARIO)
		VALUES (GETDATE(),@SALARIO,@ID_FUNC)
END
GO