CREATE DATABASE CONCESSIONARIA
GO


USE CONCESSIONARIA
GO

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL

)
GO


CREATE TABLE MODELO(
	IDMODELO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	ID_MARCA INT

)
GO


CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY IDENTITY,
	PRECO DECIMAL(10,2) NOT NULL,
	SITUACAO VARCHAR(20) DEFAULT 'DISPONIVEL',
	PLACA VARCHAR(10) UNIQUE,
	ANO INT NOT NULL,
	COR VARCHAR(15) NOT NULL,
	ID_MODELO INT


)
GO

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CHECK (SEXO IN('F','M')),
	EMAIL VARCHAR(30) NOT NULL

)
GO

CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	DATA_CONTRATACAO DATE

)
GO

CREATE TABLE FORMA_PAGAMENTO(
	IDPAGAMENTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL
)
GO


CREATE TABLE VENDAS(
	IDVENDA INT PRIMARY KEY IDENTITY,
	DATA_VENDA DATE NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_VENDEDOR INT,
	ID_PAGAMENTO INT,
	ID_CARRO INT

)
GO
