/* CONSTRAINTS */

ALTER TABLE MODELO
ADD CONSTRAINT FK_MODELO_MARCA
FOREIGN KEY (ID_MARCA) REFERENCES MARCA(IDMARCA)
GO

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MODELO
FOREIGN KEY (ID_MODELO) REFERENCES MODELO(IDMODELO)
GO


ALTER TABLE VENDAS 
ADD CONSTRAINT FK_VENDAS_PAGAMENTO
FOREIGN KEY (ID_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(IDPAGAMENTO)
GO

ALTER TABLE VENDAS 
ADD CONSTRAINT FK_VENDAS_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO

ALTER TABLE VENDAS 
ADD CONSTRAINT FK_VENDAS_VENDEDOR
FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(IDVENDEDOR)
GO

ALTER TABLE VENDAS
ADD CONSTRAINT FK_VENDAS_CARRO
FOREIGN KEY (ID_CARRO) REFERENCES CARRO(IDCARRO)
GO

ALTER TABLE CARRO
ADD CONSTRAINT CK_SITUACAO
CHECK(SITUACAO IN('VENDIDO','DISPONIVEL'))
GO