 /* CRIAÇÃO DE BANCO SO PARA BACKUPS + TABELA BACKUP PARA VENDAS + TRIGGER PARA NÃO PERDER HISTORICO DE VENDAS */

CREATE DATABASE BACKUPS
GO

USE BACKUPS

 CREATE TABLE BACKUP_VENDAS(
	IDBACKUP INT PRIMARY KEY IDENTITY,
	DATA_VENDA DATE NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT,
	ID_VENDEDOR INT,
	ID_PAGAMENTO INT,
	ID_CARRO INT,
	TIPO_OPERACAO VARCHAR(10) NOT NULL,
	DATA_OPERACAO DATETIME

 )
 GO
 

 CREATE TRIGGER TRG_BACKUP_VENDAS
 ON VENDAS
 AFTER INSERT,DELETE,UPDATE
 AS
 BEGIN
		INSERT INTO BACKUPS.dbo.BACKUP_VENDAS (DATA_VENDA,VALOR,ID_CLIENTE,ID_VENDEDOR,ID_PAGAMENTO,ID_CARRO,
										   TIPO_OPERACAO,DATA_OPERACAO)
		
		SELECT
			I.DATA_VENDA,
			I.VALOR,
			I.ID_CLIENTE,
			I.ID_VENDEDOR,
			I.ID_PAGAMENTO,
			I.ID_CARRO,
			'INSERT',
			GETDATE()
		FROM inserted I

		UNION ALL

		    -- DELETE
    SELECT 
        D.DATA_VENDA,
        D.VALOR,
        D.ID_CLIENTE,
        D.ID_VENDEDOR,
        D.ID_PAGAMENTO,
        D.ID_CARRO,
        'DELETE',
        GETDATE()
    FROM deleted D

	UNION ALL

    -- UPDATE (dados NOVOS)
    SELECT
        I.DATA_VENDA,
        I.VALOR,
        I.ID_CLIENTE,
        I.ID_VENDEDOR,
        I.ID_PAGAMENTO,
        I.ID_CARRO,
        'UPDATE',
        GETDATE()
    FROM inserted I
    INNER JOIN deleted D
        ON I.IDVENDA = D.IDVENDA

END
GO